'use client'

import { useState } from 'react'

interface EmailDraftProps {
  email: string
  academy: string
}

const academyEmails: Record<string, string> = {
  'FC Barcelona La Masia': 'youth@fcbarcelona.cat',
  'RB Leipzig Academy': 'academy@rbleipzig.com',
  'Ajax Academy': 'youth@ajax.nl',
  'Atalanta Academy': 'academy@atalanta.it',
  'Manchester City Academy': 'academy@mancity.com',
  'Borussia Dortmund Academy': 'youth@bvb.de',
}

export default function EmailDraft({ email, academy }: EmailDraftProps) {
  const [copied, setCopied] = useState(false)
  const toAddress = academyEmails[academy] || 'academy@club.com'

  const subjectMatch = email.match(/Subject:\s*(.+)/i)
  const subject = subjectMatch ? subjectMatch[1].trim() : 'Youth Talent Scouting Report'
  const body = email.replace(/Subject:\s*.+\n*/i, '').trim()

  const handleCopy = async () => {
    await navigator.clipboard.writeText(email)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="max-w-4xl mx-auto p-8">
      <h3 className="text-lg font-bold text-white mb-4">Academy Email Draft</h3>
      <div className="bg-gray-900/50 rounded-lg border border-gray-800 overflow-hidden">
        <div className="border-b border-gray-800 p-4 space-y-2">
          <div className="flex items-center gap-2 text-sm">
            <span className="text-gray-500 w-16">To:</span>
            <span className="text-blue-400">{toAddress}</span>
          </div>
          <div className="flex items-center gap-2 text-sm">
            <span className="text-gray-500 w-16">Subject:</span>
            <span className="text-white">{subject}</span>
          </div>
        </div>
        <div className="p-6 text-gray-300 whitespace-pre-wrap leading-relaxed text-sm">
          {body}
        </div>
        <div className="border-t border-gray-800 p-4 flex items-center justify-between">
          <span className="text-xs text-gray-600">This email was generated by Ghost Scout</span>
          <button
            onClick={handleCopy}
            className="px-4 py-2 text-sm font-medium rounded-lg border border-gray-700 text-gray-300 hover:border-scout-accent hover:text-scout-accent transition-colors"
            aria-label={copied ? 'Copied!' : 'Copy to clipboard'}
          >
            {copied ? 'Copied!' : 'Copy to clipboard'}
          </button>
        </div>
      </div>
    </div>
  )
}
